### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by bahoty** [scottgarner/Volotic#1]
I can run the app but there is no sound (ipad 2 / iOS 8)

**Comment by scottgarner** [comment]
Sorry to hear you're having trouble.

Were you trying to play one of the example songs or something original? Is there no sound both with and without headphones?

**Comment by bahoty** [comment]
Hello, 
I tried both demo songs and something new. I removed and installed again and rebooted my device. I haven't tried with headphones yet. I'll let you know if it changes anything...


----- Mail original -----
De: "Scott Garner" <notifications@github.com>
À: "scottgarner/Volotic" <Volotic@noreply.github.com>
Cc: "bahoty" <e.ledentu@free.fr>
Envoyé: Mercredi 28 Janvier 2015 16:08:40
Objet: Re: [Volotic] no sound (#1)



Sorry to hear you're having trouble. 

Were you trying to play one of the example songs or something original? Is there no sound both with and without headphones?

**Comment by bahoty** [comment]
I tried with headphones ans it works. There is only no sound with loudspeaker...

Emmanuel

**Comment by scottgarner** [comment]
Looks like this isn't really a Unity problem, but a problem with sound
settings on the iPad being confusing.

http://answers.unity3d.com/questions/274726/no-audio-from-ipad-speakersios-511-but-has-audio-f.html

Check the state of the mute/lock switch on the iPad and also try sliding up
from the bottom of the screen and checking the settings in that menu.

**Comment by bahoty** [comment]
Great ! Thank you for your help, it now works fine !

Emmanuel
